---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# covid19 and influenza vaccination coverage

This repository contains the scripts used to analyzed the data reported in the paper:

*Influenza Vaccination and COVID19 Mortality: Cross-sectional Trends from Italy and USA* \n

Claudio Zanettini\*, Mohamed Omar\*, Wikum Dinalankara, Eddie Luidy Imada, Elizabeth Colantuoni, Giovanni Parmigiani, and Luigi Marchionni.

# Files:

* `code/script/libraries_functions`: loads the libraries (including the one to retrieve data) and contains main functions used to analyze the data. Documentation on the arguments, and object returned by the functions is reported in the file.

* `code/scripts/us_preprocess`: this is used to obtain U.S data (using the R package `covid19census`) and preprocess them.

* `code/us_analysis`: runs the model for US Data.

---------------------------------------

# Sources and data

Details regarding the data sources as well as functions to extract updated COVID-19 data and aggregate them with other socio-economic and health related metrics can be found in the [covid19census R package](https://github.com/c1au6i0/covid19census). Please refer to the package README or documentation for more information regarding the variables.

The file `data/data.Rdata` contains a static copy of the data (one dataframe for Italy and one for U.S) used for the analysis.

The scripts used to import static data are reported in the package repository [here](https://github.com/c1au6i0/covid19census/data-raw/).
